title: Governance Handbook - ODSC
description: A draft documentation site for ODS Co-op governance (aspirational)
remote_theme: "pmarsceill/just-the-docs"

url: https://rhiaro.github.io/ods-governance-handbook